### PR TITLE
PR for old issues 64 and 48

### PR DESCRIPTION
**Pull request by eabase**
See commit messages.
 64 - Press <Tab> at the beginning of the line
 48 - Make it possible to use colored completions

### CODE REVIEW

**Comment by eabase** [comment]
No idea what this crap is al about...
> pyreadline3\test\test_vi.py:1857: AssertionError

**Comment by eabase** [comment]
My suspicion based on [this SO](https://stackoverflow.com/questions/9468435/how-to-fix-column-calculation-in-python-readline-if-using-color-prompt/9468954#9468954), is that the # 48 [here](https://github.com/pyreadline/pyreadline/pull/48) is not really needed if you apply the RL "on/off"  escapes when using colors. 

This still need to be tested. I have [a gist](https://gist.github.com/eabase/7866dd17884af428dc907b31bb20f9ff) with a fix for a standalone version of [fancycompleter](https://github.com/pdbpp/fancycompleter) that you can just import, and then run with:

```python
python.exe -qui -X utf8=1
import fancycompleter; fancycompleter.interact()
```

**Comment by eabase** [comment]
it all works. please merge

**Comment by eabase** [comment]
@brgirgis 
Please find out what's wrong with the tests. Seem that the error has nothing to do with my PR at all...

**Comment by eabase** [comment]
PR 48 works, but that there is a small issue regarding the stripping of ANSI ESC sequences, that assume a certain format, that can't be reliably assumed. This results that the strip is probably not always working correct when using ANSI coloring based on 24-bit RGB **and** using the RL on/off, and also while not using the 256 color ANSI. 

On line: 583 of basemode.py
```python
STRIPCOLOR_REGEX = re.compile(r"\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[m|K]")
```

**Comment by parejkoj** [comment]
Is there an easy fix for the 24bit color problem you mention above in the old issue 48? It would be nice to get these fixes included in the first release.

**Review by athrvvvv — APPROVED** [review]

**Review by athrvvvv — APPROVED** [review]

**Review by athrvvvv — APPROVED** [review]

**Comment by brgirgis** [comment]
Please rebase on top of `master` and push again.

**Comment by Andrej730** [comment]
Any updates on this?

**Comment by brgirgis** [comment]
I'm reverting this PR because it failed the regressions. Please submit another one.

**Pull request merged**
